### PR TITLE
Disable flowzone versioning

### PR DESCRIPTION
**Pull request by klutchell**
Signed-off-by: Kyle Harding <kyle@balena.io>

### CODE REVIEW

**Comment by churchofnoise** [comment]
Out of curiosity, is this what is causing the "plethora" of tags on docker hub? ☺️

**Comment by klutchell** [comment]
> Out of curiosity, is this what is causing the "plethora" of tags on docker hub?

It sure is. It's nice to build each architecture in a matrix job, but that means putting the images somewhere before creating a multiarch manifest. The tradeoff is worth it and I can always add some functions to clean up the old tags.

**Comment by klutchell** [comment]
The [GitHub Container Registry](https://github.com/klutchell/unbound-docker/pkgs/container/unbound) shows all identical tags on the same line, unlike Docker Hub, so it's much cleaner to look at.

**Comment by churchofnoise** [comment]
Every day is a school day, thanks for that! Learned something new.

**Comment by klutchell** [comment]
@churchofnoise and since you brought it up, all the extra tags with the git hash means that on merge or tag events, we can just add new labels to the existing images and avoid rebuilding anything! This way we can guarantee that images that have been labeled as latest or a version are the exact same images that passed testing in the PR.

**Pull request merged**
