### PR TITLE
Simplify pihole example

### LINKED ISSUE #254: Pi-hole example needs updating
For example, it still refers to `dig` in the healthcheck instead of `drill`, and with some testing it can probably be simplified.

### PR DESCRIPTION
**Pull request by garlic-hub**
Remove IP address configuration from network and let docker handle it for us. The environment variable `PIHOLE_DNS_` can resolve docker hostnames allowing us to not have to worry about IP addresses at all. Closes #254

### CODE REVIEW

**Comment by garlic-hub** [comment]
I don't use my pihole for DHCP so I can't say that I didn't break that feature

**Comment by klutchell** [comment]
> The environment variable PIHOLE_DNS_ can resolve docker hostnames

This didn't use to be the case (years ago anyway). Have you checked the official image repo to see when that changed so we can link to it for reference? I assume you've tested it with hostnames, I had no idea that was possible now.

**Comment by klutchell** [comment]
Thanks for the contributions by the way ;)

**Comment by garlic-hub** [comment]
You can see the variable documented at the top of this list here https://github.com/pi-hole/docker-pi-hole/?tab=readme-ov-file#optional-variables. It looks like that functionality came from here https://github.com/pi-hole/docker-pi-hole/commit/ae5a5afdc592968fb307257c11209d2c9f557f97

**Comment by klutchell** [comment]
> You can see the variable documented at the top of this list here https://github.com/pi-hole/docker-pi-hole/?tab=readme-ov-file#optional-variables. It looks like that functionality came from here [pi-hole/docker-pi-hole@ae5a5af](https://github.com/pi-hole/docker-pi-hole/commit/ae5a5afdc592968fb307257c11209d2c9f557f97)

TIL!

**Comment by klutchell** [comment]
This looks good to me, you'll just need to rebase after [this one](https://github.com/klutchell/unbound-docker/pull/518) merges in order to fix the tests.

**Pull request merged**
