### PR TITLE
Add rust wrapper for drill to always exit 0 or 1

### PR DESCRIPTION
**Pull request by klutchell**
Docker healthchecks expect processes to exit with 0 or 1, the other exit codes are reserved.

See: https://github.com/klutchell/unbound-docker/pull/502

### CODE REVIEW

**Comment by klutchell** [comment]
Looks like the official rust images don't support arm below armv7
https://hub.docker.com/_/rust

**Comment by garlic-hub** [comment]
armv6 is almost 25 years old, but the pi zero uses it and that's probably not a device we would want to isolate by dropping support. I wonder if dockerhub provides pull stats per architecture. I don't know anything about building docker images so I'm not sure how the buildx/bake stuff works for cross compiling other architectures. Finally, rust is on 1.81 so we would ideally use that rather than 1.76. I don't see arm support in the official Go docker image either. Do we stick with the C wrapper?

**Comment by klutchell** [comment]
Yes, I definitely don’t want to drop armv6 support so I’ll probably try another PR with the C implementation for compatibility.

**Comment by garlic-hub** [comment]
Apparently the go binary has cross compile support built in and all you need to do for armv6 is `GOARCH=arm GOARM=6 go build`. Would that be easy to change for armv7 and arm64 in the docker build?

**Pull request closed without merging**
